// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aubfxbsinraimyquktwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1YmZ4YnNpbnJhaW15cXVrdHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTI0ODEsImV4cCI6MjA2NjI2ODQ4MX0.BYf-kHAHbC3UhqOj_jkAUMkht5HO_a0Cb5x9SG26Fjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);